import{a as y,i as m,S as b}from"./assets/vendor-D73Uttp0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const L=async(s,t)=>(await y.get("https://pixabay.com/api/",{params:{key:"46731058-8e313f89df23f954200132c0b",q:s,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data,w=s=>s.map(({webformatURL:t,largeImageURL:n,tags:a,likes:e,views:r,comments:o,downloads:g})=>`
    <li class="general-list-item" >
        <a href="${n}"><img src="${t}" alt="${a}"></a>
        <div>
            <p class="general-list-item-p" ><b>Likes</b><span>${e}</span></p>
            <p class="general-list-item-p" ><b>Views</b><span>${r}</span></p>
            <p class="general-list-item-p" ><b>Comments</b><span>${o}</span></p>
            <p class="general-list-item-p" ><b>Downloads</b><span>${g}</span></p>
        </div>
    </li>
    `).join(""),v=document.querySelector("main"),f=document.forms.searchForm,q=f.elements.input,i=f.elements.submitButton,u=document.querySelector(".general-list"),p=document.querySelector("button[data-more]"),d=document.createElement("span");d.classList.add("loader");const S=15;let c,l;async function h(s,t){v.append(d),p.hidden=!0;const n=await L(s,t);if(d.remove(),!n.hits.length)throw new Error("Sorry, there are no images matching your search query. Please, try again");const a=w(n.hits);if(t===1?u.innerHTML=a:u.insertAdjacentHTML("beforeend",a),E.refresh(),t*S>=n.totalHits)throw new Error("We're sorry, but you've reached the end of search results.");p.hidden=!1,c+=1}i.addEventListener("click",async s=>{if(s.preventDefault(),l=q.value.trim(),!!l){i.disabled=!0,c=1;try{await h(l,c)}catch(t){u.innerHTML="",m.error({message:t.message,position:"topRight"})}finally{i.disabled=!1}}});p.addEventListener("click",async()=>{i.disabled=!0;try{await h(l,c);const s=document.querySelector(".general-list-item").getBoundingClientRect().height;scrollBy({top:s*2+32,behavior:"smooth"})}catch(s){m.info({message:s.message,position:"topRight"})}finally{i.disabled=!1}});const E=new b(".general-list a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=index.js.map
